[package]
name = "euphoxide"
version = "0.5.0"
edition = "2021"

[features]
bot = ["dep:async-trait", "dep:clap", "dep:cookie"]

[dependencies]
async-trait = { version = "0.1.75", optional = true }
caseless = "0.2.1"
cookie = { version = "0.18.0", optional = true }
futures-util = { version = "0.3.30", default-features = false, features = ["sink"] }
log = "0.4.20"
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.108"
time = { version = "0.3.31", features = ["serde"] }
tokio = { version = "1.35.1", features = ["time", "sync", "macros", "rt"] }
tokio-stream = "0.1.14"
tokio-tungstenite = { version = "0.21.0", features = ["rustls-tls-native-roots"] }
unicode-normalization = "0.1.22"

[dependencies.clap]
version = "4.4.11"
optional = true
default-features = false
features = ["std", "derive", "deprecated"]

[dev-dependencies] # For example bot
tokio = { version = "1.35.1", features = ["rt-multi-thread"] }

[[example]]
name = "testbot_instance"
required-features = ["bot"]

[[example]]
name = "testbot_instances"
required-features = ["bot"]

[[example]]
name = "testbot_commands"
required-features = ["bot"]
