[package]
name = "euphoxide"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.143", features = ["derive"] }
serde_json = "1.0.83"
thiserror = "1.0.32"
time = { version = "0.3.13", features = ["serde"] }
tokio = { version = "1.20.1", features = ["time", "sync", "macros", "rt"] }

[dependencies.futures]
version = "0.3.23"
default-features = false
features = ["std"]

[dependencies.tokio-tungstenite]
version = "0.17.2"
features = ["rustls-tls-native-roots"]

[dev-dependencies] # For example bot
tokio = { version = "1.20.1", features = ["rt-multi-thread"] }
