[package]
name = "euphoxide"
version = "0.5.1"
edition = "2021"

[features]
bot = ["dep:async-trait", "dep:clap", "dep:cookie"]

[dependencies]
async-trait = { version = "0.1.83", optional = true }
caseless = "0.2.1"
cookie = { version = "0.18.1", optional = true }
futures-util = { version = "0.3.31", default-features = false, features = ["sink"] }
jiff = { version = "0.1.15", features = ["serde"] }
log = "0.4.22"
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.133"
tokio = { version = "1.42.0", features = ["time", "sync", "macros", "rt"] }
tokio-stream = "0.1.16"
tokio-tungstenite = { version = "0.24.0", features = ["rustls-tls-native-roots"] }
unicode-normalization = "0.1.24"

[dependencies.clap]
version = "4.5.22"
optional = true
default-features = false
features = ["std", "derive", "deprecated"]

[dev-dependencies] # For example bot
tokio = { version = "1.42.0", features = ["rt-multi-thread"] }

[[example]]
name = "testbot_instance"
required-features = ["bot"]

[[example]]
name = "testbot_instances"
required-features = ["bot"]

[[example]]
name = "testbot_commands"
required-features = ["bot"]

[lints]
rust.unsafe_code = { level = "forbid", priority = 1 }
# Lint groups
rust.deprecated_safe = "warn"
rust.future_incompatible = "warn"
rust.keyword_idents = "warn"
rust.rust_2018_idioms = "warn"
rust.unused = "warn"
# Individual lints
rust.non_local_definitions = "warn"
rust.redundant_imports = "warn"
rust.redundant_lifetimes = "warn"
rust.single_use_lifetimes = "warn"
rust.unit_bindings = "warn"
rust.unnameable_types = "warn"
rust.unused_crate_dependencies = "warn"
rust.unused_import_braces = "warn"
rust.unused_lifetimes = "warn"
rust.unused_qualifications = "warn"
# Clippy
clippy.use_self = "warn"
