[package]
name = "euphoxide"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.147", features = ["derive"] }
serde_json = "1.0.87"
time = { version = "0.3.15", features = ["serde"] }
tokio = { version = "1.21.2", features = ["time", "sync", "macros", "rt"] }

[dependencies.futures]
version = "0.3.25"
default-features = false
features = ["std"]

[dependencies.tokio-tungstenite]
version = "0.17.2"
features = ["rustls-tls-native-roots"]

[dev-dependencies] # For example bot
tokio = { version = "1.21.2", features = ["rt-multi-thread"] }
