[package]
name = "euphoxide"
version = "0.2.0"
edition = "2021"

[features]
bot = []

[dependencies]
futures-util = { version = "0.3.25", default-features = false, features = ["sink"] }
log = "0.4.17"
serde = { version = "1.0.149", features = ["derive"] }
serde_json = "1.0.89"
time = { version = "0.3.17", features = ["serde"] }
tokio = { version = "1.23.0", features = ["time", "sync", "macros", "rt"] }
tokio-stream = "0.1.11"
tokio-tungstenite = { version = "0.18.0", features = ["rustls-tls-native-roots"] }

[dev-dependencies] # For example bot
tokio = { version = "1.23.0", features = ["rt-multi-thread"] }

[[example]]
name = "testbot_instance"
required-features = ["bot"]
